import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CraftAI - AI Powered Tools for Artisans and Creators",
  description: "Generated by create next app",
  icons: "/logo.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} xl:px-36 lg:px-24 md:px-16 sm:px-8 px-4`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
